# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
#/control/verbose 2
#/tracking/verbose 1
#/control/saveHistory
#/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 1
#
#
# Visualization setting
#/control/execute vis.mac
#/random/setSeeds 368592 58755
#/run/beamOn 1000  #100000
#/process/list
