# Set some default verbose
#/control/verbose 2
#/tracking/verbose 1
#/control/saveHistory
#/run/verbose 2
#
/process/em/verbose 0
/process/had/verbose 0
/process/verbose 0
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 12
#
# Initialize kernel
/run/initialize
#
# Visualization setting
#/control/execute vis.mac
/random/setSeeds 6589533 21755
/run/beamOn 1000000

/random/setSeeds 6469533 21755
/run/beamOn 1000000

/random/setSeeds 6229533 11755
/run/beamOn 1000000

/random/setSeeds 6589533 10755
/run/beamOn 1000000 
#/process/list
