# Set some default verbose
#/control/verbose 2
#/tracking/verbose 1
#/control/saveHistory
#/run/verbose 2
#
/process/em/verbose 0
/process/had/verbose 0
/process/verbose 0
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 12
#
# Initialize kernel
/run/initialize
#
# Visualization setting
#/control/execute vis.mac
/random/setSeeds 1576098 21456
/run/beamOn 10000000 #100000
#/process/list
